# Лабораторная работа №3

## Примеры

In [1]:
# пока n<10 прибавить к n единицу и распечатать значение:
n = 0
while n < 10
n += 1
println(n)
end

1
2
3
4
5
6
7
8
9
10


In [2]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]
i = 1
while i <= length(myfriends)
friend = myfriends[i]
println("Hi $friend, it's great to see you!")
i += 1
end

Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


In [3]:
for n in 1:2:10
println(n)
end
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]

1
3
5
7
9


5-element Vector{String}:
 "Ted"
 "Robyn"
 "Barney"
 "Lily"
 "Marshall"

In [4]:
for friend in myfriends
println("Hi $friend, it's great to see you!")
end

Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


In [5]:
# инициализация массива m x n из нулей:
m, n = 5, 5
A = fill(0, (m, n))
# формирование массива, в котором значение каждой записи
# является суммой индексов строки и столбца:
for i in 1:m
for j in 1:n
A[i, j] = i + j
end
end
A

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [6]:
# инициализация массива m x n из нулей:
B = fill(0, (m, n))
for i in 1:m, j in 1:n
B[i, j] = i + j
end
B

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [7]:
C = [i + j for i in 1:m, j in 1:n]
C

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [8]:
# используем `&&` для реализации операции "AND"
# операция % вычисляет остаток от деления
N = 7
if (N % 3 == 0) && (N % 5 == 0)
println("FizzBuzz")
elseif N % 3 == 0
println("Fizz")
elseif N % 5 == 0
println("Buzz")
else
println(N)
end

7


In [9]:
function sayhi(name)
println("Hi $name, it's great to see you!")
end
# функция возведения в квадрат:
function f(x)
x^2
end

f (generic function with 1 method)

In [10]:
sayhi("C-3PO")
f(42)

Hi C-3PO, it's great to see you!


1764

In [11]:
sayhi2(name) = println("Hi $name, it's great to see you!")
f2(x) = x^2
sayhi3 = name-> println("Hi $name, it's great to see you!")
f3 = x-> x^2

#8 (generic function with 1 method)

In [12]:
# задаём массив v:
v = [3, 5, 2]
sort(v)
v
sort!(v)
v

3-element Vector{Int64}:
 2
 3
 5

In [13]:
#Задаёмматрицу A:
A = [i + 3*j for j in 0:2, i in 1:3]
#Вызываемфункциюfвозведениявквадрат
f(A)

3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

## Выполнение заданий

In [14]:
# Задание №1

for i in 1:100
println("$i - ", i^2)
end

1 - 1
2 - 4
3 - 9
4 - 16
5 - 25
6 - 36
7 - 49
8 - 64
9 - 81
10 - 100
11 - 121
12 - 144
13 - 169
14 - 196
15 - 225
16 - 256
17 - 289
18 - 324
19 - 361
20 - 400
21 - 441
22 - 484
23 - 529
24 - 576
25 - 625
26 - 676
27 - 729
28 - 784
29 - 841
30 - 900
31 - 961
32 - 1024
33 - 1089
34 - 1156
35 - 1225
36 - 1296
37 - 1369
38 - 1444
39 - 1521
40 - 1600
41 - 1681
42 - 1764
43 - 1849
44 - 1936
45 - 2025
46 - 2116
47 - 2209
48 - 2304
49 - 2401
50 - 2500
51 - 2601
52 - 2704
53 - 2809
54 - 2916
55 - 3025
56 - 3136
57 - 3249
58 - 3364
59 - 3481
60 - 3600
61 - 3721
62 - 3844
63 - 3969
64 - 4096
65 - 4225
66 - 4356
67 - 4489
68 - 4624
69 - 4761
70 - 4900
71 - 5041
72 - 5184
73 - 5329
74 - 5476
75 - 5625
76 - 5776
77 - 5929
78 - 6084
79 - 6241
80 - 6400
81 - 6561
82 - 6724
83 - 6889
84 - 7056
85 - 7225
86 - 7396
87 - 7569
88 - 7744
89 - 7921
90 - 8100
91 - 8281
92 - 8464
93 - 8649
94 - 8836
95 - 9025
96 - 9216
97 - 9409
98 - 9604
99 - 9801
100 - 10000


In [15]:
squares = Dict{Int,Int}()
for i in 1:100
    squares[i] = i^2
end
println(length(squares))
println(squares[1])
println(squares[50])
println(squares[100])

100
1
2500
10000


In [17]:
i = 1
squares_arr = Int[]
while i <= 100
    push!(squares_arr, i^2)
    i += 1
end

println(length(squares_arr))
println(squares_arr[1])
println(squares_arr[50])
println(squares_arr[100])

100
1
2500
10000


In [24]:
# Задание №2

a = 4

if (a%2==0)
    println(a)
else
    println("нечётное")
end

4


In [25]:
x = 5

println(x % 2 == 0 ? x : "нечётное")

нечётное


In [26]:
# Задание №3

add_one(x) = x + 1

println(add_one(5))     
println(add_one(0))     
println(add_one(-1))    

6
1
0


In [27]:
# Задание №4

A = [1 1 3; 5 2 6; -2 -1 -3]

A_plus1_map = map(add_one, A)

A_plus1_bc = add_one.(A)

A_plus1 = A .+ 1

println("map:       ", A_plus1_map)
println("broadcast: ", A_plus1_bc)
println("A .+ 1:    ", A_plus1)  

map:       [2 2 4; 6 3 7; -1 0 -2]
broadcast: [2 2 4; 6 3 7; -1 0 -2]
A .+ 1:    [2 2 4; 6 3 7; -1 0 -2]


In [28]:
# Задание №5

A = [1  1  3;
     5  2  6;
    -2 -1 -3]

A3 = A^3
println("A^3 = ")
display(A3)

A_mod = copy(A)
A_mod[:, 3] = A[:, 2] .+ A[:, 3]
println("\nA с заменённым 3-м столбцом:")
display(A_mod)

A^3 = 


3×3 Matrix{Int64}:
 0  0  0
 0  0  0
 0  0  0


A с заменённым 3-м столбцом:


3×3 Matrix{Int64}:
  1   1   4
  5   2   8
 -2  -1  -4

In [29]:
# Задание №6

B = hcat(fill(10, 15), fill(-10, 15), fill(10, 15))

B = [i == 1 ? 10 : (i == 2 ? -10 : 10) for _ in 1:15, i in 1:3]

B = zeros(Int, 15, 3)
B[:, 1] .= 10
B[:, 2] .= -10
B[:, 3] .= 10

C = B' * B
println("C = BᵀB = ")
display(C)

C = BᵀB = 


3×3 Matrix{Int64}:
  1500  -1500   1500
 -1500   1500  -1500
  1500  -1500   1500

In [34]:
# Задание №7

Z = zeros(Int, 6, 6)   
E = ones(Int, 6, 6)    

Z1 = zeros(Int, 6, 6)
for i in 1:6
    for j in 1:6
        if abs(i - j) <= 1
            Z1[i, j] = 1
        end
    end
end
display(Z1)


Z2 = zeros(Int, 6, 6)
for i in 1:6
    for j in 1:6
        d = abs(i - j)
        if d <= 1 || d == 5
            Z2[i, j] = 1
        end
    end
end
display(Z2)

Z3 = zeros(Int, 6, 6)
for i in 1:6
    for j in 1:6
        s = i + j
        if s == 5 || s == 7 || s == 9 || s == 11
            Z3[i, j] = 1
        end
    end
end
display(Z3)

Z4 = zeros(Int, 6, 6)
for i in 1:6
    for j in 1:6
        if (i + j) % 2 == 0
            Z4[i, j] = 1
        end
    end
end
display(Z4)

6×6 Matrix{Int64}:
 1  1  0  0  0  0
 1  1  1  0  0  0
 0  1  1  1  0  0
 0  0  1  1  1  0
 0  0  0  1  1  1
 0  0  0  0  1  1

6×6 Matrix{Int64}:
 1  1  0  0  0  1
 1  1  1  0  0  0
 0  1  1  1  0  0
 0  0  1  1  1  0
 0  0  0  1  1  1
 1  0  0  0  1  1

6×6 Matrix{Int64}:
 0  0  0  1  0  1
 0  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0

6×6 Matrix{Int64}:
 1  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  1

In [35]:
# Задание №8

function outer(x, y, op)
    m, n = length(x), length(y)
    C = Matrix{typeof(op(x[1], y[1]))}(undef, m, n)
    for i in 1:m
        for j in 1:n
            C[i, j] = op(x[i], y[j])
        end
    end
    return C
end

x = [1, 2, 3]
y = [10, 20]
println("outer(x, y, +) ="); display(outer(x, y, +))
println("outer(x, y, *) ="); display(outer(x, y, *))
println("outer(x, y, ^) ="); display(outer(x, y, ^))

v = 0:4
A1 = outer(v, v, (a, b) -> a + b)
println("A1 ="); display(A1)

A2 = outer(0:4, 0:4, (a, b) -> a * b^2)
println("\nA2 ="); display(A2)

A3 = outer(0:4, 0:4, (a, b) -> mod(a + b, 5))
println("\nA3 ="); display(A3)

A4 = outer(0:9, 0:9, (a, b) -> mod(a + b, 10))
println("\nA4 ="); display(A4)

A5 = outer(1:9, 1:9, (a, b) -> mod(a - b, 9))
println("\nA5 ="); display(A5)

outer(x, y, +) =


3×2 Matrix{Int64}:
 11  21
 12  22
 13  23

outer(x, y, *) =


3×2 Matrix{Int64}:
 10  20
 20  40
 30  60

outer(x, y, ^) =


3×2 Matrix{Int64}:
     1           1
  1024     1048576
 59049  3486784401

A1 =


5×5 Matrix{Int64}:
 0  1  2  3  4
 1  2  3  4  5
 2  3  4  5  6
 3  4  5  6  7
 4  5  6  7  8


A2 =


5×5 Matrix{Int64}:
 0  0   0   0   0
 0  1   4   9  16
 0  2   8  18  32
 0  3  12  27  48
 0  4  16  36  64


A3 =


5×5 Matrix{Int64}:
 0  1  2  3  4
 1  2  3  4  0
 2  3  4  0  1
 3  4  0  1  2
 4  0  1  2  3


A4 =


10×10 Matrix{Int64}:
 0  1  2  3  4  5  6  7  8  9
 1  2  3  4  5  6  7  8  9  0
 2  3  4  5  6  7  8  9  0  1
 3  4  5  6  7  8  9  0  1  2
 4  5  6  7  8  9  0  1  2  3
 5  6  7  8  9  0  1  2  3  4
 6  7  8  9  0  1  2  3  4  5
 7  8  9  0  1  2  3  4  5  6
 8  9  0  1  2  3  4  5  6  7
 9  0  1  2  3  4  5  6  7  8


A5 =


9×9 Matrix{Int64}:
 0  8  7  6  5  4  3  2  1
 1  0  8  7  6  5  4  3  2
 2  1  0  8  7  6  5  4  3
 3  2  1  0  8  7  6  5  4
 4  3  2  1  0  8  7  6  5
 5  4  3  2  1  0  8  7  6
 6  5  4  3  2  1  0  8  7
 7  6  5  4  3  2  1  0  8
 8  7  6  5  4  3  2  1  0

In [36]:
# Задание №9

n = 5
A = [abs(i - j) + 1 for i in 1:n, j in 1:n]
b = [7, -1, -3, 5, 17]

x = A \ b
println("Решение: x = ", x)

# Проверка
println("A*x = ", A * x)
println("b   = ", b)

function solve_abs_system(n, b)
    A = [abs(i - j) + 1 for i in 1:n, j in 1:n]
    return A \ b
end

Решение: x = [-2.0000000000000036, 3.0000000000000058, 4.999999999999998, 1.9999999999999991, -3.999999999999999]
A*x = [7.0000000000000036, -1.0000000000000036, -3.0, 5.000000000000002, 17.0]
b   = [7, -1, -3, 5, 17]


solve_abs_system (generic function with 1 method)

In [39]:
# Задание №10

using Random
Random.seed!(42)  

M = rand(1:10, 6, 6)
println("M ="); display(M)

N = 4      
M_val = 7  
K = 75    

count_per_row = [count(>(N), M[i, :]) for i in 1:6]
println("\nЧисло элементов > $N в каждой строке:")
for i in 1:6
    println("  строка $i: $(count_per_row[i])")
end

rows_with_two = [i for i in 1:6 if count(==(M_val), M[i, :]) == 2]
println("\nСтроки, где $M_val встречается ровно 2 раза: ", rows_with_two)

col_sums = vec(sum(M, dims=1))
println("\nСуммы столбцов: ", col_sums)

pairs = Tuple{Int,Int}[]
for j1 in 1:6
    for j2 in (j1+1):6
        if col_sums[j1] + col_sums[j2] > K
            push!(pairs, (j1, j2))
        end
    end
end

println("Пары столбцов с суммой > $K: ", pairs)

M =


6×6 Matrix{Int64}:
 7  7  4  5  4  4
 5  7  3  5  4  2
 5  5  6  1  5  8
 8  3  1  6  9  4
 7  7  3  2  4  1
 2  7  2  7  6  1


Число элементов > 4 в каждой строке:
  строка 1: 3
  строка 2: 3
  строка 3: 5
  строка 4: 3
  строка 5: 2
  строка 6: 3

Строки, где 7 встречается ровно 2 раза: [1, 5, 6]

Суммы столбцов: [34, 36, 19, 26, 32, 20]
Пары столбцов с суммой > 75: Tuple{Int64, Int64}[]


In [40]:
# Задание №11

S1 = sum(i^4 / (3 + j) for i in 1:20, j in 1:5)
println("S1 = ", S1)

S2 = sum(i^4 / (3 + i*j) for i in 1:20, j in 1:5)
println("S2 = ", S2)

S1 = 639215.2833333338
S2 = 89912.02146097131
